name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: ["py3.5", "py3.6", "py3.7", "py3.8", "nightly"]
        include:
          - name: "py3.5"
            python: "3.5"
            tox_env: "du12"
          - name: "py3.6"
            python: "3.6"
            tox_env: "du13"
          - name: "py3.7"
            python: "3.7"
            tox_env: "du14"
          - name: "py3.8"
            python: "3.8"
            tox_env: "du15"
            use_coverage: true
          - name: "nightly"
            python: "3.10-dev"
            tox_env: "du16"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        if: "!endsWith(matrix.python, '-dev')"
        with:
          python-version: ${{ matrix.python }}
      - name: Set up Python ${{ matrix.python }} (deadsnakes)
        uses: deadsnakes/action@v1.0.0
        if: endsWith(matrix.python, '-dev')
        with:
          python-version: ${{ matrix.python }}
      - name: Check Python version
        run: python --version
      - name: Install graphviz
        run: sudo apt-get install graphviz
      - name: Install dependencies
        run: pip install -U tox codecov
      - name: Run tox
        run: tox -e ${{ matrix.tox_env }} -- -vv
      - name: codecov
        if: matrix.use_coverage
        env:
          PYTEST_ADDOPTS: "--cov ./ --cov-append --cov-config setup.cfg"
        run: codecov -e ${{ matrix.tox_env }}

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: pip install -U tox
      - name: Run Tox
        run: tox -e py -- -vv
